server:
    port: 8080
    contextPath: /swim/api/v1

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/swim?autoReconnect=true
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
        maxActive: 10
        max-idle: 5
        min-idle: 1
        test-while-idle: true
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
    level:
        org:
            prnhs: DEBUG
            springframework: ERROR